defaultIndent: "    "
removeTrailingWhitespace: 1

# Keep list indentation consistent
indentAfterItems:
  itemize: 1
  enumerate: 1
  description: 1

indentRules:
  itemize: "  "
  enumerate: "  "
  description: "  "
